{figure} = PredatorScar [ScarPredator.dae]
{figure} = PredatorJungleHunter [JungleHunterPredator.dae]
{figure} = PredatorWolf [WolfPredator.dae]
{figure} = PredatorFalconer [FalconerPredator.dae]
{figure} = PredatorBerserker [BerserkerPredator.dae]
{figure} = PredatorHound [PredatorHound.dae]
{figure} = PredatorTracker [TrackerPredator.dae]
{figure} = PredatorCamoCloakBerserker [CamoCloakBerserkerPredator.dae]
{figure} = PredatorClassic [ClassicPredator.dae]
{figure} = PredatorClassicGort [ClassicGortPredator.dae]
{figure} = PredatorElder [ElderPredator.dae]
{figure} = PredatorCityHunter [CityHunterPredator.dae]
{figure} = PredatorShaman [ShamanPredator.dae]
{figure} = PredatorCityHunter2 [CityHunter2Predator.dae]
{figure} = PredatorBoar [BoarPredator.dae]
{figure} = PredatorStalker [StalkerPredator.dae]
{figure} = PredatorSnake [SnakePredator.dae]
{figure} = PredatorGurdian [GurdianPredator.dae]
{figure} = PredatorWarrior [WarriorPredator.dae]
{figure} = PredatorLost [LostPredator.dae]
{figure} = PredatorScout [ScoutPredator.dae]
{figure} = PredatorBigRed [BigRedPredator.dae]
{figure} = PredatorCityHunter7 [CityHunter7Predator.dae]
{figure} = PredatorAlbino [AlbinoPredator.dae]
{figure} = PredatorHiveWars [HiveWarsPredator.dae]
{figure} = PredatorNightstorm [NightstormPredator.dae]
{figure} = PredatorLavaPlanet [LavaPlanetPredator.dae]
{figure} = PredatorWasp [WaspPredator.dae]
Mode.loc:[Start]
{mode} = [cloaked]//:Berserkerpredator//[Berserkercloaked.dae]//:<>
{mode} = [cloaked]//:ClassicPredator//[Classicpredatorcloaked.dae]//:<>
{mode} = [cloaked]//:CityPredator//[Citypredatorcloaked.dae]//:<>
{mode} = [cloaked]//:Wolfpredator//[Wolfpredatorcloaked.dae]//:<>
{mode} = [cloaked]//:Falconerpredator//[Falconerpredatorcloaked.dae]//:<>
{mode} = [cloaked]//:CamoCloakpredator//[Camocloakpredatorcloaked.dae]//:<>
{mode} = [cloaked]//:Wolfpredator//[Wolfpredatorcloaked.dae]//:<>
{mode} = [dress]//:Classicpredator//[Classicpredatormask.dae]//:<>
{mode} = [dress]//:Classicpredator//[Classicpredatordamage.dae]//:<>
{mode} = [dress]//:[add].{all_predator}.[Mask]
{mode} = [dress]//:[add].{all_predator}.[Damage]
